CREATE TABLE products(id INTEGER PRIMARY KEY AUTOINCREMENT, url TEXT UNIQUE NOT NULL, name TEXT, active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE prices(product_id INTEGER NOT NULL, day TEXT NOT NULL, price INTEGER NOT NULL, source TEXT NOT NULL, PRIMARY KEY(product_id,day));
CREATE TABLE jobs(id INTEGER PRIMARY KEY AUTOINCREMENT, key TEXT UNIQUE NOT NULL, kind TEXT NOT NULL, value TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', attempts INTEGER NOT NULL DEFAULT 0, leased_at INTEGER, created_at INTEGER NOT NULL DEFAULT (unixepoch()));
CREATE TABLE alerts(product_id INTEGER NOT NULL, day TEXT NOT NULL, PRIMARY KEY(product_id,day));
CREATE TABLE budget(day TEXT PRIMARY KEY, used INTEGER NOT NULL DEFAULT 0);
